# =============================================================================
# HYDRA-UMC-BRIDGE-PRINTER3D - Read-only slicer artifact tests
# Copyright (C) 2026 JuanenRac (Electro Hobby 3D) <electrohobby3d@gmail.com>
# GPL-3.0-or-later - see LICENSE
# =============================================================================
import tempfile
import unittest
from pathlib import Path

from hydra_umc_bridge_printer3d.artifacts import PrintArtifactKind, PrintTechnology, inspect_artifact


class PrintArtifactTests(unittest.TestCase):
    def inspect_named(self, name: str, contents: bytes):
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / name
            path.write_bytes(contents)
            return inspect_artifact(path)

    def test_orcaslicer_gcode_is_identified_without_command_parsing(self):
        artifact = self.inspect_named("cube.gcode", b"; generated by OrcaSlicer\nG1 X10 Y10\n")
        self.assertEqual(artifact.kind, PrintArtifactKind.FDM_GCODE)
        self.assertEqual(artifact.technology, PrintTechnology.FDM)
        self.assertEqual(artifact.source_hint, "OrcaSlicer")
        self.assertIn("no command was parsed", artifact.message)

    def test_cura_prusa_and_bambu_markers_are_recognized(self):
        cases = ((b";Generated with Cura_SteamEngine\n", "Ultimaker Cura"), (b"; generated by PrusaSlicer\n", "PrusaSlicer"), (b"; BambuStudio\n", "Bambu Studio"))
        for contents, expected in cases:
            with self.subTest(expected=expected):
                self.assertEqual(self.inspect_named("job.gcode", contents).source_hint, expected)

    def test_gcode_3mf_is_not_unpacked(self):
        artifact = self.inspect_named("job.gcode.3mf", b"not a zip and never unpacked")
        self.assertEqual(artifact.kind, PrintArtifactKind.FDM_GCODE_3MF)
        self.assertEqual(artifact.technology, PrintTechnology.FDM)
        self.assertEqual(artifact.source_hint, "unknown-slicer")

    def test_generic_3mf_is_a_project_not_a_print_command(self):
        artifact = self.inspect_named("project.3mf", b"project package")
        self.assertEqual(artifact.kind, PrintArtifactKind.PROJECT_3MF)
        self.assertEqual(artifact.technology, PrintTechnology.UNKNOWN)

    def test_resin_slice_is_opaque_and_never_attributed_to_lychee(self):
        artifact = self.inspect_named("part.ctb", b"binary resin slice")
        self.assertEqual(artifact.kind, PrintArtifactKind.RESIN_SLICE)
        self.assertEqual(artifact.technology, PrintTechnology.RESIN)
        self.assertEqual(artifact.source_hint, "unknown-slicer")

    def test_unknown_and_missing_artifacts_fail_closed(self):
        self.assertEqual(self.inspect_named("part.stl", b"model").kind, PrintArtifactKind.UNKNOWN)
        self.assertFalse(inspect_artifact(Path("definitely-missing.gcode")).available)


if __name__ == "__main__":
    unittest.main()
