# =============================================================================
# HYDRA-UMC-BRIDGE-PRINTER3D - Print artifact profile boundary tests
# Copyright (C) 2026 JuanenRac (Electro Hobby 3D) <electrohobby3d@gmail.com>
# GPL-3.0-or-later - see LICENSE
# =============================================================================
import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

from hydra_umc_bridge_printer3d.artifacts import PrintArtifact, PrintArtifactKind, PrintTechnology
from hydra_umc_bridge_printer3d.profiles import PrintProfile, assess_artifact_profile


def artifact(kind: PrintArtifactKind, technology: PrintTechnology) -> PrintArtifact:
    return PrintArtifact(True, kind, technology, "test", "read-only evidence", 1, "a" * 64)


class PrintProfileTests(unittest.TestCase):
    def setUp(self):
        self.fdm_profile = PrintProfile("fdm-lab", PrintTechnology.FDM, frozenset({PrintArtifactKind.FDM_GCODE}))

    def test_matching_evidence_never_authorizes_execution(self):
        assessment = assess_artifact_profile(self.fdm_profile, artifact(PrintArtifactKind.FDM_GCODE, PrintTechnology.FDM))
        self.assertTrue(assessment.profile_compatible)
        self.assertFalse(assessment.execution_authorized)

    def test_wrong_technology_or_kind_is_rejected(self):
        self.assertFalse(assess_artifact_profile(self.fdm_profile, artifact(PrintArtifactKind.RESIN_SLICE, PrintTechnology.RESIN)).profile_compatible)
        self.assertFalse(assess_artifact_profile(self.fdm_profile, artifact(PrintArtifactKind.FDM_GCODE_3MF, PrintTechnology.FDM)).profile_compatible)

    def test_missing_profile_identifier_is_rejected(self):
        profile = PrintProfile(" ", PrintTechnology.FDM, frozenset({PrintArtifactKind.FDM_GCODE}))
        self.assertFalse(assess_artifact_profile(profile, artifact(PrintArtifactKind.FDM_GCODE, PrintTechnology.FDM)).profile_compatible)

    def test_offline_cli_reports_match_but_never_execution_authorization(self):
        root = Path(__file__).resolve().parent.parent
        with tempfile.TemporaryDirectory() as directory:
            workspace = Path(directory)
            profile_path = workspace / "profile.json"
            artifact_path = workspace / "job.gcode"
            profile_path.write_text(json.dumps({"profile_id": "lab-fdm", "technology": "fdm", "accepted_kinds": ["fdm-gcode"]}), encoding="utf-8")
            artifact_path.write_text("; generated by OrcaSlicer\n", encoding="utf-8")
            completed = subprocess.run([sys.executable, str(root / "tools" / "assess_print_profile.py"), str(profile_path), str(artifact_path)], text=True, capture_output=True, check=False)
        self.assertEqual(completed.returncode, 0, completed.stderr)
        result = json.loads(completed.stdout)
        self.assertTrue(result["profile_compatible"])
        self.assertFalse(result["execution_authorized"])


if __name__ == "__main__":
    unittest.main()
